export const API_PATHS = {
  GUESTS: '/api/guests',
  GUEST: (id: string) => `/api/guests/${encodeURIComponent(id)}`,
  GUEST_CONFIG: (id: string) => `/api/guests/${encodeURIComponent(id)}/config`,
  GUEST_ACTION: (id: string) => `/api/guests/${encodeURIComponent(id)}/action`,
  GUEST_REFRESH: (id: string) => `/api/guests/${encodeURIComponent(id)}/refresh`,
  GUEST_OS_UPDATE: (id: string) => `/api/guests/${encodeURIComponent(id)}/os-update`,
  GUEST_APP_UPDATE: (id: string) => `/api/guests/${encodeURIComponent(id)}/app-update`,
  GUEST_BACKUP: (id: string) => `/api/guests/${encodeURIComponent(id)}/backup`,
  HOST_BACKUP_STORAGES: (hostId: string) => `/api/settings/hosts/${encodeURIComponent(hostId)}/backup-storages`,
  REFRESH: '/api/refresh',
  SETTINGS_FULL: '/api/settings/full',
  SETTINGS: '/api/settings',
  SETTINGS_TEST_CONNECTION: '/api/settings/test-connection',
  APP_CONFIG_DEFAULTS: '/api/app-config/defaults',
  GITHUB_TEST: '/api/github/test',
  NOTIFICATIONS_TEST: '/api/notifications/test',
  CUSTOM_APPS: '/api/custom-apps',
  CUSTOM_APP: (id: string) => `/api/custom-apps/${encodeURIComponent(id)}`,
  AUTH_STATUS: '/api/auth/status',
  AUTH_LOGIN: '/api/auth/login',
  AUTH_LOGOUT: '/api/auth/logout',
  AUTH_CHANGE_PASSWORD: '/api/auth/change-password',
  SETUP_STATUS: '/api/setup/status',
  HEALTH: '/health',
  TASKS: '/api/tasks',
} as const;
